### ISSUE TITLE
Colorful GUIS with color message!

### ISSUE THREAD

**Issue by abreubacelar** [pd-externals/tipoftheday-plugin#36]
### Detail

```plain text
It is possible to change the color of gui-objects via a color message. The message consists of three parameters, one for the color of the background, one for the front (when a bang is clicked, for example) and the last for the label of the GUI. You can provide a simple number from 0 to 29 to select a preset (the colors from properties menu), or provide a rgb color like #00ff7f. Check the helpfiles of the guis for more examples on how to change its properties!
```

### Image

![tipoftheday-bangcolors](https://user-images.githubusercontent.com/16086370/202911740-056ad200-be71-472d-87e8-3f920ea546bc.gif)

**Comment by porres** [comment]
this is an outdated/deprecated way to set colors, the help file describes this. Also, I don't see this as something particularly worth noting here.

**Comment by abreubacelar** [comment]
> this is an outdated/deprecated way to set colors, the help file describes this. Also, I don't see this as something particularly worth noting here.

hmm, i thought that the deprecated way was using negative numbers, i used the preset representation in the gif, and also said about hex colors in the detail text, and invited the user to read more in the helpfile.

**Comment by umlaeute** [comment]
I don't think it's "deprecated".
There may be more convenient ways to set colours for only e.g background (though I haven't actually checked), but I don't think there's anything inherently wrong with the way your are showing here.

**Comment by umlaeute** [comment]
@porres wrote:
> Also, I don't see this as something particularly worth noting here.

So what? Tip-of-the-day are supposed to informally document things that are easily missed otherwise. That doesn't mean that that they aren't documented (even though the help patches are quite verbose about setting colours via messages, I guess most people use the dialog to change a colours of an iemgui. And as such, they probably forget about the messages).

Personally I wouldn't have thought about adding this tip, but this is precisely the reason why people can easily submit there own.
So please create and submit *your* tips. (And if we ever have too many tips, we can always revise them)

**Comment by porres** [comment]
yeah, I see it, you're right. I've been thinking about it and cannot actually think of good tips of the day so far. I'll spend more time on it, but I'm hoping to find more useful and obscure things than this.

**Comment by porres** [comment]
> hmm, i thought that the deprecated way was using negative numbers

yeah, that's true! Sorry. But I also think hexadecimal is the more "oficial" one, so maybe use at least both options?
